services:
  - type: web
    name: mcp-google-ads-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health/keyword-ideas
    healthCheckTimeout: 10
    autoDeploy: true
    envVars:
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        sync: false
      - key: GOOGLE_ADS_CREDENTIALS_PATH
        sync: false
      - key: GOOGLE_ADS_LOGIN_CUSTOMER_ID
        sync: false
      - key: GOOGLE_ADS_AUTH_TYPE
        value: service_account
      - key: TEST_CUSTOMER_ID
        value: "9197949842"
      - key: DEPLOYMENT_ENVIRONMENT
        value: production
    secrets:
      - key: GOOGLE_ADS_CREDENTIALS_JSON
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block" 